---
title: "lab7 reposicion"
author: "Mayco"
date: "2024-11-16"
output: github_document
---

```{r setup, include=FALSE}
library(readr)  
library(dplyr)  
library(stringr)  
library(lubridate)  
library(stopwords)  
library(wordcloud) 
library(tidytext)
```

```{r include=FALSE}
metadata <- read_csv("Health_and_Personal_Care_metadata.csv")

reviews <- read_csv("Health_and_Personal_Care.csv")
```

## 1) Cuántos productos contienen reviews con las palabras “love”, “recommend” y “enjoy”?

```{r}
words <- c("love", "recommend", "enjoy" )
reviews_filtrados <- na.omit(reviews)

reviews_filtrados <- reviews %>% 
  filter(str_detect(tolower(text), paste(words, collapse = "|")))

num_productos <- reviews_filtrados %>% 
  distinct(product_id) %>% 
  count()

num_productos

```

## 2.	De los reviews de la pregunta 1, encuentre el top 5 de las tiendas que los venden?

```{r}

reviews_tiendas <- reviews_filtrados %>%
  left_join(metadata, by = "parent_id")

top_5_tiendas <- reviews_tiendas %>%
  filter(!is.na(store)) %>%       
  group_by(store) %>%  
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  slice(1:5)

top_5_tiendas
```

## 3.	Genere un wordcloud sin stopwords de los reviews de la pregunta 1.

```{r}
stop_vec <- c(stopwords("en"), stopwords("es"))

frecuencias <- reviews_filtrados %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_vec, word != "br") %>% 
  count(word, sort = TRUE)

# Wordcloud
set.seed(123)
wordcloud(
  words = frecuencias$word,
  freq = frecuencias$n,
  min.freq = 2,
  max.words = 100,
  random.order = FALSE,
  colors = brewer.pal(8, "Set1")
)
```

## 4.	Wordcloud de los reviews de las 5 tiendas encontradas en la pregunta 2. 

```{r}

stop_vec <- c(stopwords("en"), stopwords("es"))

frecuencias_top <- reviews %>%
  left_join(metadata[, c("parent_id", "store")], by = "parent_id") %>%
  filter(store %in% top_5_tiendas$store) %>%
  mutate(text = as.character(text)) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_vec, word != "br") %>%
  count(word, sort = TRUE)

# Generar el wordcloud
set.seed(123)
wordcloud(words = frecuencias_top$word,
          freq = frecuencias_top$n,
          min.freq = 2,
          max.words = 100,
          random.order = FALSE,
          colors = brewer.pal(8, "Set1"))

```


## 5) 25 palabras más frecuentes de los reviews

```{r}
top_25_palabras <- reviews %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words, by = "word") %>%
  count(word, sort = TRUE) %>%
  filter(word != "br") %>% 
  slice_head(n = 25)

top_25_palabras
```





